---
galaxy_info:
  author: Arkadiusz Kondas
  description: Installs and configure PHP on Debian/Ubuntu servers
  license: MIT
  min_ansible_version: 1.9
  platforms:
    - name: Ubuntu
      versions:
      - all
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - php
    - web