---
configs: &configs
  vm_box: &configs_vm_box
    'ubuntu/xenial64'                        # image name; trusty=14.04; xenial=16.04; xenial=16.04; zesty=17.04;
  vm_name: &configs_vm_name
    'project.local'                            # None special characters
  vm_memory: &configs_vm_memory
    1024                                     # RAM memory - recommend > 1024
  vm_cpus: &configs_vm_cpus
    1                                        # CPUs
  vm_ip: &configs_vm_ip
    '63.63.63.63'                            #ip VM
  vm_url: &configs_vm_url
    'project.local'                            #url
  vm_path: &configs_vm_path
    '/var/www/project.local'                   #default path
  project_root: &configs_project_root
    '/var/www/project.local/public'            #default path site
  prod_url: &configs_prod_url
    'project.local'                            #prod url for replace on database Search replace
  prod_path: &configs_prod_path
    ''                                       #prod url for replace on database Search replace

php:
  ppa: "ppa:ondrej/php"
  name_version: "php7.3"
  version: "7.3"
  packages:
    - php7.3-common
    - php7.3-cli
    - php7.3-intl
    - php7.3-curl
    - php7.3-mysql
    - php7.3-readline
    #- mcrypt
    - php7.3-json
    - php7.3-mbstring
    - php7.3-xml
    - php7.3-zip
    - php7.3-gd
    - php7.3-fpm
  timezone: Europe/Dublin
  upload_max_filesize: "100M"
  post_max_size: "100M"
  memory_limit: "512M"
  fpmsocket: "/run/php/php7.3-fpm.sock"

apache2:
  docroot: *configs_project_root
  servername: *configs_vm_url

nginx:
  docroot: *configs_project_root
  servername: *configs_vm_url

mysql:
  root_password: '123'
  database: project_database
  user: projectuser
  password: '123'
  dump: ''

ohmyzsh:
  theme: 'agnoster'

nodejs:
  version: 9.11.2
  npm: 5.6

vagrant_local:
  vm:
    base_box: *configs_vm_box
    hostname: *configs_vm_name
    ip: *configs_vm_ip
    memory: *configs_vm_memory
    sharedfolder: ./
    useVagrantCloud: '1'
    syncType: '0'

server:
  packages:
    - vim
    - git
    - htop
    - unzip
    - curl
  timezone: Europe/Dublin
  locale: en_US.UTF-8
