- name: oh-my-zsh | Clone down repository
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/ubuntu/.oh-my-zsh

- name: oh-my-zsh | Remove standard .zshrc
  become: yes
  become_method: root
  file: path=/home/ubuntu/.zshrc state=absent

- name: oh-my-zsh | Deploy new .zshrc
  become: yes
  become_method: root
  template: src=zshrc.in dest=/home/ubuntu/.zshrc owner=ubuntu

- name: oh-my-zsh | Set zsh as default shell
  user: name=ubuntu shell=/bin/zsh

- name: Permissions
  file: path=/home/ubuntu state=directory owner=ubuntu group=ubuntu mode=0775
  become: yes
  become_method: sudo