- name: oh-my-zsh | Clone down repository
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh

- name: oh-my-zsh | Remove standard .zshrc
  become: yes
  become_method: root
  file: path=/home/vagrant/.zshrc state=absent

- name: oh-my-zsh | Deploy new .zshrc
  become: yes
  become_method: root
  template: src=zshrc.in dest=/home/vagrant/.zshrc owner=vagrant

- name: oh-my-zsh | Set zsh as default shell
  user: name=vagrant shell=/bin/zsh

- name: Permissions
  file: path=/home/vagrant state=directory owner=vagrant group=vagrant mode=0775
  become: yes
  become_method: sudo