---
- name: Add PPA Repository
  become: yes
  become_method: root
  apt_repository: repo={{ php.ppa }}

- name: Update apt
  become: yes
  become_method: root
  apt:
    update_cache: yes

- name: Install PHP
  become: yes
  become_method: root
  apt:
    pkg: "{{ php.name_version }}"
    state: latest
    update_cache: yes

- name: Install PHP Packages
  become: yes
  become_method: root
  apt:
    pkg: "{{ php.packages }}"
    state: latest
    update_cache: yes
  when: php.packages is defined
  notify:
    - restart php-fpm
