---
- name: Add PPA Repository
  become: yes
  become_method: root
  apt_repository: repo={{ php.ppa }}

- name: Update apt
  become: yes
  become_method: root
  apt: update_cache=yes

- name: Install PHP
  become: yes
  become_method: root
  apt: pkg={{ php.name_version }} state=latest

- name: Install PHP Packages
  become: yes
  become_method: root
  apt: pkg={{ php.name_version }}-{{ item }} state=latest
  with_items:
    "{{ php.packages }}"
  when: php.packages is defined
  notify:
    - restart php-fpm
